from __future__ import annotations

import logging

import streamlit as st

import api_client

logger = logging.getLogger(__name__)


def _render_sources(sources: list[dict]) -> None:
    with st.expander(f"Sources & Citations ({len(sources)})"):
        for i, src in enumerate(sources):
            score = src.get("score", 0.0)
            filename = src.get("filename", "unknown")
            chunk_idx = src.get("chunk_index", 0)
            chunk_text = src.get("chunk_text", "")

            col1, col2, col3 = st.columns([3, 1, 1])
            col1.markdown(f"**{filename}**")
            col2.markdown(f"Chunk: `{chunk_idx}`")
            col3.markdown(f"Score: `{score:.1f}`")

            preview = chunk_text[:300] + ("..." if len(chunk_text) > 300 else "")
            st.caption(preview)

            if i < len(sources) - 1:
                st.markdown("---")


def _render_usage(usage: dict | None) -> None:
    if not usage:
        return

    breakdown: list[dict] = usage.get("breakdown", [])
    total_tokens = usage.get("total_tokens", 0)
    total_cost = usage.get("total_cost_usd", 0.0)
    total_latency = usage.get("total_latency_ms", 0.0)

    with st.expander(
        f"Token Usage  |  {total_tokens:,} tokens  |  ${total_cost:.6f}  |  {total_latency:.0f} ms"
    ):
        # Summary row
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Tokens", f"{total_tokens:,}")
        col2.metric("Total Cost (USD)", f"${total_cost:.6f}")
        col3.metric("Total Latency", f"{total_latency:.0f} ms")

        st.markdown("#### Breakdown by Action")

        # Table header
        hcols = st.columns([2, 1, 1, 1, 1, 1, 1])
        for col, label in zip(
            hcols,
            ["Action", "Tokens In", "Tokens Out", "Total Tokens", "% of Total", "Cost (USD)", "Latency (ms)"],
        ):
            col.markdown(f"**{label}**")

        st.markdown("---")

        for row in breakdown:
            action = row.get("action", "")
            tok_in = row.get("tokens_in", 0)
            tok_out = row.get("tokens_out", 0)
            tok_total = row.get("total_tokens", 0)
            pct = row.get("pct_of_total_tokens", 0.0)
            cost = row.get("cost_usd", 0.0)
            latency = row.get("latency_ms", 0.0)

            rcols = st.columns([2, 1, 1, 1, 1, 1, 1])
            rcols[0].markdown(f"`{action}`")
            rcols[1].markdown(str(tok_in))
            rcols[2].markdown(str(tok_out))
            rcols[3].markdown(str(tok_total))
            rcols[4].markdown(f"{pct:.1f}%")
            rcols[5].markdown(f"${cost:.6f}")
            rcols[6].markdown(f"{latency:.0f} ms")


def _render_message(msg: dict) -> None:
    role = msg["role"]
    with st.chat_message(role):
        st.markdown(msg["content"])

        if role == "assistant":
            if msg.get("skipped_generation"):
                st.warning("Insufficient context — could not generate an answer from the available documents.")

            if msg.get("injection_detected"):
                st.info("Potential prompt injection detected in your query. It was neutralized before processing.")

            model = msg.get("model_used", "")
            if model == "gemini-fallback":
                st.caption("Generated by: Gemini (Claude unavailable)")
            elif model == "claude":
                st.caption("Generated by: Claude")

            sources = msg.get("sources", [])
            if sources:
                _render_sources(sources)

            _render_usage(msg.get("usage"))


def render_chat(collection_name: str | None) -> None:
    st.subheader("Chat")

    if collection_name is None:
        st.info("Select a collection in the sidebar to start chatting.")
        return

    history_key = f"chat_history_{collection_name}"
    if history_key not in st.session_state:
        st.session_state[history_key] = []

    history: list[dict] = st.session_state[history_key]

    # Declare chat_input before rendering messages — Streamlit pins it to the bottom
    question = st.chat_input(f"Ask a question about '{collection_name}'...")

    for msg in history:
        _render_message(msg)

    if question:
        user_msg = {"role": "user", "content": question}
        history.append(user_msg)
        _render_message(user_msg)

        with st.chat_message("assistant"):
            with st.spinner("Searching and generating answer..."):
                try:
                    result = api_client.query_collection(
                        collection_name, question,
                        reranking=st.session_state.get("reranking_enabled", True),
                    )
                except Exception:
                    logger.error("Query failed for collection '%s'", collection_name, exc_info=True)
                    st.error("Query failed. Check logs for details.")
                    history.append({"role": "assistant", "content": "Error: query failed", "sources": []})
                    return

            assistant_msg = {
                "role": "assistant",
                "content": result.get("answer", ""),
                "sources": result.get("sources", []),
                "confidence": result.get("confidence", 0.0),
                "model_used": result.get("model_used", ""),
                "skipped_generation": result.get("skipped_generation", False),
                "injection_detected": result.get("injection_detected", False),
                "usage": result.get("usage"),
            }
            history.append(assistant_msg)

            st.markdown(assistant_msg["content"])

            if assistant_msg["skipped_generation"]:
                st.warning("Insufficient context — could not generate an answer from the available documents.")

            if assistant_msg["injection_detected"]:
                st.info("Potential prompt injection detected in your query. It was neutralized before processing.")

            model = assistant_msg["model_used"]
            if model == "gemini-fallback":
                st.caption("Generated by: Gemini (Claude unavailable)")
            elif model == "claude":
                st.caption("Generated by: Claude")

            if assistant_msg["sources"]:
                _render_sources(assistant_msg["sources"])

            _render_usage(assistant_msg.get("usage"))
